global:
  scrape_interval: 5s  # Set the interval to scrape targets

scrape_configs:
  - job_name: 'python_app'
    static_configs:
      - targets: ['47.129.101.238:8000']  # Adjust to match the Python app’s metrics endpoint
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['47.129.101.238:9100']